# Peakfit steering code
#
# Remember that yaml scientific notation requires 1.0 (dots)
# and (+) and (-) for the exponent (e.g. 1.0e+8)
#
#
# Tips: One can simplify the model by settings some parameters to
# their "symmetric" (e.g. 0) values and fixing those.
#
# m.mieskolainen@imperial.ac.uk, 2022

#path:     '/home/user/fitdata/flat/muon/generalTracks/JPsi'
#path:     '/vols/cms/jd918/LLP/CMSSW_10_2_18/src/TagAndProbe_14Sep22_hack/flat/muon/generalTracks/JPsi'
path:     '/vols/cms/jd918/LLP/CMSSW_10_2_18/src/TagAndProbe_14Dec22/flat/muon/generalTracks/JPsi'
fitrange: [2.8, 3.4] # GeV
years: [2016]

fit:

  S:
    func:    'CB_asym_RBW_conv_pdf'
    args:    
      norm:     True
      Nmin:     256 # minimum number of function samples for convolution integral
      xfactor:  0.2 # extra domain extension factor for convolution integral (0.2 gives 20%)

    w_start:  100.0
    w_limit:  [1.0e-4, 1.0e+5]
    w_fixed:  False

    # Gamma(J/psi) = 9.32e-05 GeV (very narrow!)
    # CB_param   = par[0],par[1],par[2],par[3] ~ Crystal-Ball detector smearing x radiative
    # aRBW_param = par[0],par[4],par[5]        ~ J/Psi resonance ~ [initial state pdf x form factor x breit-wigner]
    
    p_name:   ['M0', 'sigma', 'n', 'alpha', 'Gamma', 'asym']
    p_start:  [3.097, 0.02, 1.001, 1.3, 1.0e-4, -0.01]
    p_limit:  [[3.085, 3.1], [0.01, 0.05], [1.001, 2.0], [0.1, 2.0], [9.32e-5, 0.05], [-10.0, 10.0]]
    p_fixed:  [False, False, False, False, False, False]
    
  B:
    func:    'exp_pdf'
    args:
      norm:     True
      #Nmin:     null # not active
    
    w_start:  1.0e-3
    w_limit:  [1.0e-4, 1.0e+5]
    w_fixed:  False

    p_name:   ['lambda']
    p_start:  [1.0e-4]
    p_limit:  [[1.0e-5, 4.0]]
    p_fixed:  [False]


  # Add here more fit components in linear superposition, by giving a unique string label
  # ...


# Fit algorithm parameters
techno:
  losstype: 'nll'              # 'chi2' or 'nll'
  use_limits: True             # Use parameter bounds
  zerobin: 1.0e-2              # Minimum number of counts in a valid bin
  
  # Use at least 10k iterations (otherwise can get stuck in bad local minima)
  
  ncall_simplex_scipy: 10000   # Number of scipy search calls
  ncall_scan:     1000         # Number of brute force scan calls
  ncall_simplex:  20000        # Number of Nelder-Mead simplex search calls
  ncall_gradient: 10000        # Number of Minuit gradient search calls
  
  
  hesse: True       # Minuit HESSE uncertainties
  minos: False      # Minuit MINOS uncertainties

  max_chi2: 1200    # Maximum chi2/ndf for a succesful fit
  min_count: 5      # Minimum number of entries in the histogram
  max_trials: 3     # Number of restarts

  set_to_nan: True  # Set parameters after the fit to NaN if not passing max_chi2 or min_count

  strategy: 1       # Default 1
  tol: 0.1          # Default 0.1, https://iminuit.readthedocs.io/en/stable/reference.html#iminuit.Minuit.tol
